import 'dart:ui';

import 'package:flutter/material.dart';

const kColorPrimary = Color(0xff0B2443);
const kColorPrimary50 = Color(0xff800B2443);
const kColorLight = Color(0xffefefef);
const kColorPrimaryDark = Color(0xff0B203C);
const kColorAccent = Color(0xff02B8A5);
const kColorAccent20 = Color(0xff3302B8A5);
const kColorAccentLight = Color(0xffE5F8F6);
const kColorAccentDark = Color(0xff029F8E);
const kColorBlack = Color(0xff000000);
const kColorWhite = Color(0xffFFFFFF);
const kColorWhite80 = Color(0xccffffff);
const kPrimaryText = Color(0xffde000000);
const kSecondaryText = Color(0xff8a000000);
const kTertiaryText = Color(0xff61000000);
const kColorDivider = Color(0xff1f000000);
const kColorBackground = Color(0xffe8eaec);
const kColorYellow = Color(0xffFFEB3B);
const kColorRating = Color(0xffFFC027);
const kColorEditTextHint = Color(0xffA7B4CA);
const kColorEditTextBorder = Color(0xffD5E0F0);
const kColorTabTextColor = Color(0xffB3FFFFFF);
const kColorGrey500 = Color(0xff9e9e9e);
const kColorGrey400 = Color(0xffbdbdbd);
const kColorGrey300 = Color(0xffe0e0e0);
const kColorGrey200 = Color(0xffeeeeee);
const kColorGrey100 = Color(0xfff5f5f5);
const kColorErrorIcon = Color(0xffC3C4C8);
const kColorPendingText = Color(0xff555555);
const kColorDeactivate = Color(0xffFFE2DC);
const kColorDeactivateText = Color(0xffF16042);
const kColorDisabled = Color(0xffEEEEEE);
const kColorDisabledText = Color(0xffd2d2d2);
const kColorFabIcon = Color(0xff494949);
const kColorIconFilter = Color(0xff636363);
const kColorBgConclude = Color(0xffAAAAAA);
const kColorBgOngoing = Color(0xffE38F28);
const kColorBgUpcoming = Color(0xff46A848);
const kColorBgCancelled = Color(0xffF16042);
const kColorLegendBackground = Color(0xffF5F5F5);
const kColorLegendBooked = kColorAccent;
const kColorLegendAvailable = Color(0xfffafafa);
const kColorLegendNotAvailable = Color(0xffDDDDDD);
const kColorLegendSelected = Color(0xffE7EEFA);
const kColorError = Colors.redAccent;
const kColorRed = Color(0xffF44336);
const kColorCardHeader = Color(0xffEFF1F0);
const kColorRedAccent = Color(0xfffd7f7f);
const kColorGrayish = Color(0xffF0F0F0);
const kColorAccentLight1 = Color(0xffCCF1ED);
const kColorAppBarIcon = Color(0xff999999);
const kColorAppBarTitle = Color(0xff212121);
const kColorBlackText = Color(0xff212121);
const kColorSubHeading = Color(0xff999999);



class HudleColorV2 {
  static const kScaffoldBackground = Color(0xFFF4F5F8);
  static const kColorSecondary = Color(0xFF1D517F);
  static const kColorSecondaryDark = Color(0xFF0B2443);
  static const kColorSecondaryLight = Color(0xFFE6EBF0);
  static const kColorSecondaryLighter = Color(0xFFF1F5F7);
  static const kColorOnSecondary = Color(0xFFFFFFFF);
  static const kColorPrimary = Color(0xFF02B8A5);
  static const kColorPrimaryDark = Color(0xFF00A392);
  static const kColorPrimaryLight = Color(0xFF80DBD2);
  static const kColorPrimaryLighter = Color(0xFFCCF1ED);
  static const kColorPrimaryLighten = Color(0xFFF0FAF9);
  static const kColorOnPrimary = Color(0xFFFFFFFF);
  static const kPrimaryTextColor = Color(0xff212121);
  static const kSecondaryTextColor = Color(0xff999999);
  static const kTertiaryTextColor = Color(0xffBBBBBB);
  static const kHighlightTextColor = Color(0xffF0F0F0);
  static const kShadowColor = Color(0x1A1D517F);
  static const kColorOnBackground = kPrimaryTextColor;
  static const kColorRed = Color(0xFFF04534);
  static const kColorYellow = Color(0xFFF4DA45);
  static const kColorViolet = Color(0xFF8656F0);
  static const kColorOrange = Color(0xFFFF8A00);
  static const kColorBrown = Color(0xFF955B31);
  //Gradients
  static const kSecondaryStartColor = Color(0xFF80DBD2);
  static const kSecondaryEndColor = Color(0xFF02B8A5);
  static const kPrimaryStartColor = Color(0xFF1D517F);
  static const kPrimaryEndColor = Color(0xFF2F7FC7);
  static const kPrimaryVariantStartColor = Color(0xFF88C8E0);
  static const kPrimaryVariantEndColor = Color(0xFF066CA2);
  static const k_StartColor = Color(0xFF);
  static const k_EndColor = Color(0xFF);
  static const kVioletStartColor = Color(0xFFBE88E0);
  static const kVioletEndColor = Color(0xFF5A06A2);
  static const kGreenStartColor = Color(0xFF7CB93F);
  static const kGreenEndColor = Color(0xFF557621);
  static const kSecondaryVariantStartColor = Color(0xFF45CBC9);
  static const kSecondaryVariantEndColor = Color(0xFF178D80);
  static const kRedStartColor = Color(0xFFE08888);
  static const kRedEndColor = Color(0xFFB4274D);
  static const kBrownStartColor = Color(0xFFE3AC75);
  static const kBrownEndColor = Color(0xFFBE6812);
  static const kYellowStartColor = Color(0xFFF4DA45);
  static const kYellowEndColor = Color(0xFFFF8A00);
  static const kColorAppBarTitle = Color(0xff212121);
  static const kColorAppBarIcon = Color(0xff999999);


}